### ISSUE TITLE
Voir des produits

### ISSUE THREAD

**Issue by Ant-man74** [Ant-man74/HeraWebMono#11]
Critère d’acceptante:

V1 :
> Lorsque le site se charge, des produits sont visible sur la première page avec un placeholder et un nom

V2: 
Lorsque le site se charge, des produits sont visible sous forme d'une liste sur la première page. Un affichage produit consiste au moins d'une image placeholder un nom un prix et un bouton d'ajout au panier (le bouton n'a pas à être fonctionnel). La page doit être accessible sans être identifié sur le site

Pensez à la réutilisation futur du code

**Comment by Ant-man74** [comment]
Ne répond pas au critères d'acceptance, lors du 1er démarrage aucun produit ne s'affiche, je vais préciser le critère d'aceptance

**Comment by Cieldara** [comment]
OK pour moi, attention cependant, les produits créés dans Initizlbdmigration n'ont pas d'URL d'image, à rajouter
